version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Google.Protobuf
    versions:
    - 3.15.0
    - 3.15.2
    - 3.15.4
    - 3.15.7
  - dependency-name: Microsoft.AspNetCore.Hosting.WindowsServices
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Grpc.Tools
    versions:
    - 2.36.4
  - dependency-name: Grpc.Core
    versions:
    - 2.36.4
  - dependency-name: Microsoft.AspNetCore.Mvc.NewtonsoftJson
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Serilog.AspNetCore
    versions:
    - 4.0.0
  - dependency-name: Serilog.Extensions.Hosting
    versions:
    - 4.0.0
    - 4.1.0
    - 4.1.1
  - dependency-name: Grpc.AspNetCore
    versions:
    - 2.35.0
  - dependency-name: Grpc.Net.Client
    versions:
    - 2.35.0
